name: Build CI DOTNET

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Altere para a versão do .NET que você está usando

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore **/*.csproj

      # Step 4: Build the project
      - name: Build .NET project
        run: dotnet build **/*.csproj --no-restore
